/**
 * Single source of truth for the products shown on every catalog listing page.
 * Detail pages (lib/products/data.ts) merge these with hand-written detailed
 * entries — listing pages render from these arrays directly.
 */

export interface ApiItem    { name: string; cas: string; grade: string; category: string }
export interface IntermediateItem { name: string; cas: string; purity: string; category: string }
export interface IndustrialItem   { name: string; cas: string; grade: string; category: string }
export interface ExcipientItem    { name: string; cas: string; grade: string; use: string }
export interface HerbalItem       { name: string; standardisation: string; cas: string; category: string }
export interface NutraceuticalItem{ name: string; cas: string; grade: string; category: string }
export interface FoodItem         { name: string; cas: string; eno: string; category: string; use: string }
export interface DyeItem          { name: string; cas: string; ci: string; category: string; use: string }
export interface ImpurityItem     { name: string; cas: string; api: string; grade: string }
export interface OrganicInorganicItem { name: string; cas: string; grade: string; type: 'Organic' | 'Inorganic' }
export interface PelletItem      { name: string; size: string; type: string; use: string }

export const apiListing: ApiItem[] = [
  { name: 'Abacavir Sulfate',           cas: '188062-50-2',  grade: 'USP',    category: 'Antiviral' },
  { name: 'Acetaminophen (Paracetamol)',cas: '103-90-2',     grade: 'USP/BP', category: 'Analgesic' },
  { name: 'Acyclovir',                  cas: '59277-89-3',   grade: 'USP/BP', category: 'Antiviral' },
  { name: 'Amlodipine Besylate',        cas: '111470-99-6',  grade: 'USP',    category: 'Cardiovascular' },
  { name: 'Amoxicillin Trihydrate',     cas: '61336-70-7',   grade: 'BP/EP',  category: 'Antibiotic' },
  { name: 'Aspirin',                    cas: '50-78-2',      grade: 'USP/BP', category: 'Analgesic' },
  { name: 'Atorvastatin Calcium',       cas: '134523-00-5',  grade: 'USP',    category: 'Cardiovascular' },
  { name: 'Azithromycin',               cas: '83905-01-5',   grade: 'USP/BP', category: 'Antibiotic' },
  { name: 'Cetirizine HCl',             cas: '83881-51-0',   grade: 'USP',    category: 'Antihistamine' },
  { name: 'Ciprofloxacin HCl',          cas: '86393-32-0',   grade: 'USP/BP', category: 'Antibiotic' },
  { name: 'Clarithromycin',             cas: '81103-11-9',   grade: 'USP/EP', category: 'Antibiotic' },
  { name: 'Diclofenac Sodium',          cas: '15307-79-6',   grade: 'BP/EP',  category: 'NSAID' },
  { name: 'Doxycycline Hyclate',        cas: '24390-14-5',   grade: 'USP',    category: 'Antibiotic' },
  { name: 'Esomeprazole Magnesium',     cas: '161796-78-7',  grade: 'USP/EP', category: 'GI' },
  { name: 'Fluconazole',                cas: '86386-73-4',   grade: 'USP/BP', category: 'Antifungal' },
  { name: 'Gabapentin',                 cas: '60142-96-3',   grade: 'USP',    category: 'Neurological' },
  { name: 'Ibuprofen',                  cas: '15687-27-1',   grade: 'USP/BP', category: 'NSAID' },
  { name: 'Ivermectin',                 cas: '70288-86-7',   grade: 'USP',    category: 'Antiparasitic' },
  { name: 'Losartan Potassium',         cas: '124750-99-8',  grade: 'USP',    category: 'Cardiovascular' },
  { name: 'Metformin HCl',              cas: '1115-70-4',    grade: 'USP/BP', category: 'Antidiabetic' },
  { name: 'Metronidazole',              cas: '443-48-1',     grade: 'USP/BP', category: 'Antibiotic' },
  { name: 'Montelukast Sodium',         cas: '151767-02-1',  grade: 'USP',    category: 'Respiratory' },
  { name: 'Omeprazole',                 cas: '73590-58-6',   grade: 'USP/BP', category: 'GI' },
  { name: 'Pantoprazole Sodium',        cas: '138786-67-1',  grade: 'USP/EP', category: 'GI' },
  { name: 'Paracetamol',                cas: '103-90-2',     grade: 'USP/BP', category: 'Analgesic' },
  { name: 'Pioglitazone HCl',           cas: '112529-15-4',  grade: 'USP',    category: 'Antidiabetic' },
  { name: 'Pregabalin',                 cas: '148553-50-8',  grade: 'USP',    category: 'Neurological' },
  { name: 'Ranitidine HCl',             cas: '66357-59-3',   grade: 'USP/BP', category: 'GI' },
  { name: 'Rosuvastatin Calcium',       cas: '147098-20-2',  grade: 'USP',    category: 'Cardiovascular' },
  { name: 'Salbutamol Sulfate',         cas: '51022-70-9',   grade: 'BP/EP',  category: 'Respiratory' },
  { name: 'Sertraline HCl',             cas: '79617-96-2',   grade: 'USP',    category: 'CNS' },
  { name: 'Sildenafil Citrate',         cas: '171599-83-0',  grade: 'USP',    category: 'Cardiovascular' },
  { name: 'Simvastatin',                cas: '79902-63-9',   grade: 'USP',    category: 'Cardiovascular' },
  { name: 'Tamoxifen Citrate',          cas: '54965-24-1',   grade: 'BP/EP',  category: 'Oncology' },
  { name: 'Valsartan',                  cas: '137862-53-4',  grade: 'USP/EP', category: 'Cardiovascular' },
  { name: 'Vitamin C (Ascorbic Acid)',  cas: '50-81-7',      grade: 'USP/BP', category: 'Vitamin' },
  { name: 'Zinc Sulfate Heptahydrate',  cas: '7446-20-0',    grade: 'USP',    category: 'Supplement' },
]

export const intermediatesListing: IntermediateItem[] = [
  { name: '2-Amino-5-Nitrothiazole',              cas: '121-66-4',    purity: '99%+',  category: 'Thiazole' },
  { name: '2-Chloro-5-Chloromethyl Pyridine',     cas: '70258-18-3',  purity: '98%+',  category: 'Pyridine' },
  { name: '3-Cyanopyridine',                       cas: '100-54-9',    purity: '99%+',  category: 'Pyridine' },
  { name: '4-Amino Diphenylamine',                 cas: '101-54-2',    purity: '98%+',  category: 'Amine' },
  { name: '4-Chloro-3-Nitrobenzotrifluoride',      cas: '121-17-5',    purity: '99%+',  category: 'Aromatic' },
  { name: '4-Fluorobenzaldehyde',                  cas: '459-57-4',    purity: '99%+',  category: 'Aldehyde' },
  { name: '4-Methylpiperazine-1-carboxaldehyde',   cas: '7755-92-2',   purity: '98%+',  category: 'Piperazine' },
  { name: 'Benzimidazole',                         cas: '51-17-2',     purity: '99%+',  category: 'Heterocycle' },
  { name: 'Benzyl Chloride',                       cas: '100-44-7',    purity: '99%+',  category: 'Halide' },
  { name: 'Chloroacetyl Chloride',                 cas: '79-04-9',     purity: '99%+',  category: 'Halide' },
  { name: 'Chlorobenzene',                         cas: '108-90-7',    purity: '99%+',  category: 'Aromatic' },
  { name: 'Diethyl Carbonate',                     cas: '105-58-8',    purity: '99%+',  category: 'Ester' },
  { name: 'Dimethyl Sulfoxide (DMSO)',              cas: '67-68-5',     purity: '99.9%', category: 'Solvent' },
  { name: 'Ethyl Bromoacetate',                    cas: '105-36-2',    purity: '98%+',  category: 'Ester' },
  { name: 'Guanidine Carbonate',                   cas: '593-85-1',    purity: '99%+',  category: 'Guanidine' },
  { name: 'Imidazole',                             cas: '288-32-4',    purity: '99%+',  category: 'Heterocycle' },
  { name: 'Malononitrile',                         cas: '109-77-3',    purity: '99%+',  category: 'Nitrile' },
  { name: 'N-Methylpiperazine',                    cas: '109-01-3',    purity: '99%+',  category: 'Piperazine' },
  { name: 'Nitrobenzene',                          cas: '98-95-3',     purity: '99%+',  category: 'Aromatic' },
  { name: 'Piperazine Anhydrous',                  cas: '110-85-0',    purity: '99%+',  category: 'Piperazine' },
  { name: 'Piperidine',                            cas: '110-89-4',    purity: '99%+',  category: 'Heterocycle' },
  { name: 'Pyridine',                              cas: '110-86-1',    purity: '99.8%', category: 'Pyridine' },
  { name: 'Sodium Azide',                          cas: '26628-22-8',  purity: '99%+',  category: 'Inorganic' },
  { name: 'Triethyl Orthoformate',                 cas: '122-51-0',    purity: '98%+',  category: 'Ester' },
]

export const industrialListing: IndustrialItem[] = [
  { name: 'Acetic Acid (Glacial)',     cas: '64-19-7',    grade: 'LR/AR',   category: 'Acid' },
  { name: 'Acetone',                   cas: '67-64-1',    grade: 'LR/AR',   category: 'Ketone' },
  { name: 'Ammonium Chloride',         cas: '12125-02-9', grade: 'LR',      category: 'Inorganic' },
  { name: 'Benzene',                   cas: '71-43-2',    grade: 'LR/AR',   category: 'Aromatic' },
  { name: 'Boric Acid',                cas: '10043-35-3', grade: 'LR',      category: 'Inorganic' },
  { name: 'Calcium Chloride',          cas: '10043-52-4', grade: 'LR',      category: 'Inorganic' },
  { name: 'Carbon Tetrachloride',      cas: '56-23-5',    grade: 'LR/AR',   category: 'Halide' },
  { name: 'Chloroform',                cas: '67-66-3',    grade: 'LR/AR',   category: 'Halide' },
  { name: 'Citric Acid Monohydrate',   cas: '5949-29-1',  grade: 'LR/Food', category: 'Acid' },
  { name: 'Diethyl Ether',             cas: '60-29-7',    grade: 'LR/AR',   category: 'Ether' },
  { name: 'Dimethylformamide (DMF)',   cas: '68-12-2',    grade: 'LR/AR',   category: 'Amide' },
  { name: 'Ethanol (Absolute)',        cas: '64-17-5',    grade: 'LR/AR',   category: 'Alcohol' },
  { name: 'Ethyl Acetate',             cas: '141-78-6',   grade: 'LR/AR',   category: 'Ester' },
  { name: 'Formaldehyde Solution 37%', cas: '50-00-0',    grade: 'LR',      category: 'Aldehyde' },
  { name: 'Glycerol (Glycerin)',        cas: '56-81-5',    grade: 'LR/USP',  category: 'Alcohol' },
  { name: 'Hexane (n-Hexane)',          cas: '110-54-3',   grade: 'LR/AR',   category: 'Alkane' },
  { name: 'Hydrochloric Acid 35%',     cas: '7647-01-0',  grade: 'LR/AR',   category: 'Acid' },
  { name: 'Hydrogen Peroxide 30%',     cas: '7722-84-1',  grade: 'LR/AR',   category: 'Oxidant' },
  { name: 'Isopropyl Alcohol (IPA)',   cas: '67-63-0',    grade: 'LR/AR',   category: 'Alcohol' },
  { name: 'Methanol',                  cas: '67-56-1',    grade: 'LR/AR',   category: 'Alcohol' },
  { name: 'Methylene Chloride (DCM)',  cas: '75-09-2',    grade: 'LR/AR',   category: 'Halide' },
  { name: 'Nitric Acid 70%',           cas: '7697-37-2',  grade: 'LR/AR',   category: 'Acid' },
  { name: 'Oxalic Acid',               cas: '144-62-7',   grade: 'LR',      category: 'Acid' },
  { name: 'Perchloric Acid 70%',       cas: '7601-90-3',  grade: 'AR',      category: 'Acid' },
  { name: 'Potassium Hydroxide',       cas: '1310-58-3',  grade: 'LR',      category: 'Base' },
  { name: 'Sodium Bicarbonate',        cas: '144-55-8',   grade: 'LR/Food', category: 'Inorganic' },
  { name: 'Sodium Chloride',           cas: '7647-14-5',  grade: 'LR',      category: 'Inorganic' },
  { name: 'Sodium Hydroxide',          cas: '1310-73-2',  grade: 'LR/AR',   category: 'Base' },
  { name: 'Sulfuric Acid 98%',         cas: '7664-93-9',  grade: 'LR/AR',   category: 'Acid' },
  { name: 'Toluene',                   cas: '108-88-3',   grade: 'LR/AR',   category: 'Aromatic' },
  { name: 'Xylene (Mixed)',            cas: '1330-20-7',  grade: 'LR/AR',   category: 'Aromatic' },
]

export const excipientListing: ExcipientItem[] = [
  { name: 'Avicel PH 101 (MCC)',                  cas: '9004-34-6',  grade: 'NF/Ph.Eur',     use: 'Binder / Diluent' },
  { name: 'Avicel PH 102 (MCC)',                  cas: '9004-34-6',  grade: 'NF/Ph.Eur',     use: 'Direct Compression' },
  { name: 'Calcium Phosphate Dibasic',             cas: '7757-93-9',  grade: 'USP/NF',        use: 'Diluent' },
  { name: 'Carboxymethylcellulose Sodium',         cas: '9004-32-4',  grade: 'USP/NF',        use: 'Disintegrant / Binder' },
  { name: 'Carbopol 934P',                        cas: '54182-57-9', grade: 'NF/Ph.Eur',     use: 'Thickener / Gel Former' },
  { name: 'Colloidal Silicon Dioxide (Aerosil)',   cas: '7631-86-9',  grade: 'NF',            use: 'Glidant' },
  { name: 'Croscarmellose Sodium',                 cas: '74811-65-7', grade: 'USP/NF',        use: 'Disintegrant' },
  { name: 'Crospovidone (PVPP)',                   cas: '25249-54-1', grade: 'USP/NF',        use: 'Disintegrant' },
  { name: 'HPMC (Hydroxypropyl Methylcellulose)', cas: '9004-65-3',  grade: 'USP/NF',        use: 'Binder / Film Coat' },
  { name: 'Lactose Monohydrate',                  cas: '64044-51-5', grade: 'USP/NF/Ph.Eur', use: 'Diluent' },
  { name: 'Magnesium Stearate',                   cas: '557-04-0',   grade: 'NF/Ph.Eur',     use: 'Lubricant' },
  { name: 'Mannitol',                             cas: '69-65-8',    grade: 'USP/NF',        use: 'Diluent / Sweetener' },
  { name: 'Microcrystalline Cellulose (MCC)',     cas: '9004-34-6',  grade: 'USP/NF',        use: 'Binder / Filler' },
  { name: 'Poloxamer 188 (Pluronic F68)',         cas: '9003-11-6',  grade: 'NF',            use: 'Emulsifier / Solubiliser' },
  { name: 'Polyethylene Glycol 400 (PEG 400)',    cas: '25322-68-3', grade: 'NF',            use: 'Plasticiser / Solvent' },
  { name: 'Polyethylene Glycol 6000',             cas: '25322-68-3', grade: 'NF',            use: 'Lubricant / Binder' },
  { name: 'Polyvinyl Alcohol (PVA)',               cas: '9002-89-5',  grade: 'USP',           use: 'Film Coat / Binder' },
  { name: 'Povidone K-30 (PVP)',                   cas: '9003-39-8',  grade: 'USP/NF',        use: 'Binder / Solubiliser' },
  { name: 'Sodium Lauryl Sulfate (SLS)',           cas: '151-21-3',   grade: 'NF',            use: 'Wetting Agent / Emulsifier' },
  { name: 'Sodium Starch Glycolate',              cas: '9063-38-1',  grade: 'USP/NF',        use: 'Disintegrant' },
  { name: 'Sorbitol',                             cas: '50-70-4',    grade: 'USP/NF',        use: 'Sweetener / Diluent' },
  { name: 'Starch (Maize / Corn)',                cas: '9005-25-8',  grade: 'NF/Ph.Eur',     use: 'Disintegrant / Binder' },
  { name: 'Stearic Acid',                         cas: '57-11-4',    grade: 'NF',            use: 'Lubricant' },
  { name: 'Sucrose',                              cas: '57-50-1',    grade: 'NF/Food',       use: 'Sweetener / Diluent' },
  { name: 'Talc (Pharma Grade)',                  cas: '14807-96-6', grade: 'USP/NF',        use: 'Glidant / Lubricant' },
  { name: 'Titanium Dioxide',                     cas: '13463-67-7', grade: 'NF/Food',       use: 'Opacifier' },
]

export const herbalListing: HerbalItem[] = [
  { name: 'Aloe Vera Extract',              standardisation: '20:1 Dry Extract',                    cas: '85507-69-3',  category: 'Botanical' },
  { name: 'Amla Extract',                   standardisation: '40% Tannins',                         cas: '225234-05-9', category: 'Ayurvedic' },
  { name: 'Andrographis Extract',           standardisation: '10% Andrographolide',                 cas: '5508-58-7',   category: 'Ayurvedic' },
  { name: 'Ashwagandha Root Extract',       standardisation: '2.5%/5% Withanolides',                cas: '244819-29-2', category: 'Ayurvedic' },
  { name: 'Bacopa Monnieri Extract',        standardisation: '20%/50% Bacosides',                   cas: '93913-35-0',  category: 'Ayurvedic' },
  { name: 'Berberine HCl',                  standardisation: '97%+ HPLC',                           cas: '633-65-8',    category: 'Alkaloid' },
  { name: 'Bilberry Extract',               standardisation: '25% Anthocyanosides',                 cas: '84082-34-8',  category: 'Botanical' },
  { name: 'Black Pepper Extract (Piperine)', standardisation: '95% Piperine',                       cas: '94-62-2',     category: 'Alkaloid' },
  { name: 'Boswellia Serrata Extract',      standardisation: '65% Boswellic Acids',                 cas: '89913-01-3',  category: 'Ayurvedic' },
  { name: 'Centella Asiatica Extract',      standardisation: '40% Asiaticoside',                    cas: '16830-15-2',  category: 'Botanical' },
  { name: 'Chamomile Flower Extract',       standardisation: '1.2% Apigenin',                       cas: '84082-60-0',  category: 'Botanical' },
  { name: 'Curcumin (from Turmeric)',       standardisation: '95% Curcuminoids',                    cas: '458-37-7',    category: 'Ayurvedic' },
  { name: 'Echinacea Purpurea Extract',     standardisation: '4% Echinacoside',                     cas: '90028-20-9',  category: 'Botanical' },
  { name: 'Garlic Extract',                 standardisation: '2% Allicin',                          cas: '539-86-6',    category: 'Botanical' },
  { name: 'Ginger Root Extract',            standardisation: '5% Gingerols',                        cas: '84696-15-1',  category: 'Botanical' },
  { name: 'Ginkgo Biloba Extract',          standardisation: '24% Flavone Glycosides',              cas: '90045-36-6',  category: 'Botanical' },
  { name: 'Ginseng Root Extract (Korean)', standardisation: '5% Ginsenosides',                     cas: '90045-38-8',  category: 'Adaptogen' },
  { name: 'Grape Seed Extract',             standardisation: '95% OPC',                             cas: '84929-27-1',  category: 'Antioxidant' },
  { name: 'Green Coffee Bean Extract',      standardisation: '50% Chlorogenic Acid',                cas: '327-97-9',    category: 'Botanical' },
  { name: 'Green Tea Extract',              standardisation: '98% Polyphenols / 50% EGCG',          cas: '84650-60-2',  category: 'Antioxidant' },
  { name: 'Gymnema Sylvestre Extract',      standardisation: '25% Gymnemic Acids',                  cas: '90045-47-9',  category: 'Ayurvedic' },
  { name: 'Holy Basil (Tulsi) Extract',     standardisation: '2% Ursolic Acid',                     cas: '84775-71-3',  category: 'Ayurvedic' },
  { name: 'Milk Thistle Extract (Silymarin)', standardisation: '70%/80% Silymarin',                 cas: '65666-07-1',  category: 'Botanical' },
  { name: 'Moringa Leaf Extract',           standardisation: '20:1 Dry Extract',                    cas: '84929-70-4',  category: 'Botanical' },
  { name: 'Neem Leaf Extract',              standardisation: '0.3% Azadirachtin',                   cas: '11141-17-6',  category: 'Ayurvedic' },
  { name: 'Rhodiola Rosea Extract',         standardisation: '3% Rosavins / 1% Salidroside',        cas: '84954-28-9',  category: 'Adaptogen' },
  { name: 'Senna Leaf Extract',             standardisation: '20% Sennosides',                      cas: '8013-11-4',   category: 'Botanical' },
  { name: 'Tribulus Terrestris Extract',    standardisation: '40% Saponins',                        cas: '90131-68-3',  category: 'Botanical' },
  { name: 'Valerian Root Extract',          standardisation: '0.8% Valerenic Acid',                 cas: '72968-49-1',  category: 'Botanical' },
]

export const nutraceuticalListing: NutraceuticalItem[] = [
  { name: 'Ascorbic Acid (Vitamin C)',        cas: '50-81-7',    grade: 'USP/Food', category: 'Vitamins' },
  { name: 'Biotin (Vitamin B7)',               cas: '58-85-5',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Calcium Carbonate',                 cas: '471-34-1',   grade: 'USP',      category: 'Minerals' },
  { name: 'Calcium Citrate',                   cas: '813-94-5',   grade: 'USP',      category: 'Minerals' },
  { name: 'Cholecalciferol (Vitamin D3)',       cas: '67-97-0',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Choline Bitartrate',                cas: '87-67-2',    grade: 'USP',      category: 'Amino Acids' },
  { name: 'Chromium Picolinate',               cas: '14639-25-9', grade: 'USP',      category: 'Minerals' },
  { name: 'Coenzyme Q10 (Ubiquinone)',         cas: '303-98-0',   grade: 'USP',      category: 'Antioxidants' },
  { name: 'DHA Omega-3',                       cas: '6217-54-5',  grade: 'USP',      category: 'Fatty Acids' },
  { name: 'Ferrous Fumarate',                  cas: '141-01-5',   grade: 'USP',      category: 'Minerals' },
  { name: 'Folic Acid (Vitamin B9)',           cas: '59-30-3',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Glucosamine Sulfate',               cas: '14999-43-0', grade: 'USP',      category: 'Joint Health' },
  { name: 'Inositol',                          cas: '87-89-8',    grade: 'USP',      category: 'Vitamins' },
  { name: 'L-Arginine',                        cas: '74-79-3',    grade: 'USP/Food', category: 'Amino Acids' },
  { name: 'L-Carnitine L-Tartrate',            cas: '36687-82-8', grade: 'USP',      category: 'Amino Acids' },
  { name: 'L-Glutamine',                       cas: '56-85-9',    grade: 'USP',      category: 'Amino Acids' },
  { name: 'L-Leucine',                         cas: '61-90-5',    grade: 'USP/Food', category: 'Amino Acids' },
  { name: 'L-Lysine HCl',                      cas: '657-27-2',   grade: 'USP/Food', category: 'Amino Acids' },
  { name: 'Lutein',                            cas: '127-40-2',   grade: 'USP',      category: 'Carotenoids' },
  { name: 'Lycopene',                          cas: '502-65-8',   grade: 'USP',      category: 'Carotenoids' },
  { name: 'Magnesium Citrate',                 cas: '3344-18-1',  grade: 'USP',      category: 'Minerals' },
  { name: 'Magnesium Stearate',                cas: '557-04-0',   grade: 'NF',       category: 'Excipients' },
  { name: 'Melatonin',                         cas: '73-31-4',    grade: 'USP',      category: 'Sleep Support' },
  { name: 'Niacinamide (Vitamin B3)',          cas: '98-92-0',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Pyridoxine HCl (Vitamin B6)',       cas: '58-56-0',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Quercetin',                         cas: '117-39-5',   grade: 'USP',      category: 'Antioxidants' },
  { name: 'Resveratrol',                       cas: '501-36-0',   grade: 'USP',      category: 'Antioxidants' },
  { name: 'Riboflavin (Vitamin B2)',           cas: '83-88-5',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Selenium Yeast',                    cas: '7783-00-8',  grade: 'USP',      category: 'Minerals' },
  { name: 'Thiamine HCl (Vitamin B1)',         cas: '67-03-8',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Vitamin B12 (Cyanocobalamin)',      cas: '68-19-9',    grade: 'USP',      category: 'Vitamins' },
  { name: 'Vitamin E (dl-Alpha Tocopherol)',   cas: '10191-41-0', grade: 'USP',      category: 'Vitamins' },
  { name: 'Zinc Gluconate',                    cas: '4468-02-4',  grade: 'USP',      category: 'Minerals' },
  { name: 'Zinc Sulfate Monohydrate',          cas: '7446-19-7',  grade: 'USP',      category: 'Minerals' },
]

export const foodListing: FoodItem[] = [
  { name: 'Acesulfame Potassium (Ace-K)', cas: '55589-62-3', eno: 'E950', category: 'Sweetener',    use: 'Zero-calorie sweetener' },
  { name: 'Acetic Acid (Food Grade)',     cas: '64-19-7',    eno: 'E260', category: 'Preservative', use: 'Acidulant / Preservative' },
  { name: 'Ascorbic Acid (Food Grade)',   cas: '50-81-7',    eno: 'E300', category: 'Antioxidant',  use: 'Antioxidant / Vitamin C' },
  { name: 'Aspartame',                    cas: '22839-47-0', eno: 'E951', category: 'Sweetener',    use: 'Intense sweetener' },
  { name: 'Benzoic Acid',                 cas: '65-85-0',    eno: 'E210', category: 'Preservative', use: 'Antimicrobial preservative' },
  { name: 'Beta-Cyclodextrin',            cas: '7585-39-9',  eno: '—',   category: 'Encapsulant',  use: 'Flavour encapsulation' },
  { name: 'Calcium Propionate',           cas: '4075-81-4',  eno: 'E282', category: 'Preservative', use: 'Bread & bakery preservative' },
  { name: 'Carrageenan',                  cas: '9000-07-1',  eno: 'E407', category: 'Stabiliser',   use: 'Gelling / Thickening' },
  { name: 'Citric Acid Anhydrous',        cas: '77-92-9',    eno: 'E330', category: 'Acidulant',    use: 'Acidulant / Antioxidant' },
  { name: 'Erythritol',                   cas: '149-32-6',   eno: 'E968', category: 'Sweetener',    use: 'Bulk sweetener (zero calorie)' },
  { name: 'Glycerol Monostearate (GMS)',  cas: '31566-31-1', eno: 'E471', category: 'Emulsifier',   use: 'Emulsifier / Anti-staling' },
  { name: 'Guar Gum',                     cas: '9000-30-0',  eno: 'E412', category: 'Hydrocolloid', use: 'Thickener / Stabiliser' },
  { name: 'Lactic Acid',                  cas: '50-21-5',    eno: 'E270', category: 'Acidulant',    use: 'Acidulant / Preservative' },
  { name: 'Lecithin (Soy)',               cas: '8002-43-5',  eno: 'E322', category: 'Emulsifier',   use: 'Emulsifier / Anti-stick' },
  { name: 'Malic Acid',                   cas: '6915-15-7',  eno: 'E296', category: 'Acidulant',    use: 'Flavour enhancer / Acidulant' },
  { name: 'Maltodextrin',                 cas: '9050-36-6',  eno: '—',   category: 'Carrier',      use: 'Carrier / Bulking agent' },
  { name: 'Mono & Diglycerides',          cas: '68990-53-4', eno: 'E471', category: 'Emulsifier',   use: 'Emulsifier / Softener' },
  { name: 'Potassium Sorbate',            cas: '24634-61-5', eno: 'E202', category: 'Preservative', use: 'Antifungal preservative' },
  { name: 'Sodium Benzoate',              cas: '532-32-1',   eno: 'E211', category: 'Preservative', use: 'Antimicrobial preservative' },
  { name: 'Sodium Citrate',               cas: '68-04-2',    eno: 'E331', category: 'Acidulant',    use: 'Buffer / Emulsifier' },
  { name: 'Sodium Stearoyl Lactylate',    cas: '25383-99-7', eno: 'E481', category: 'Emulsifier',   use: 'Dough strengthener' },
  { name: 'Sorbic Acid',                  cas: '110-44-1',   eno: 'E200', category: 'Preservative', use: 'Antifungal / Antibacterial' },
  { name: 'Sorbitol (Food Grade)',         cas: '50-70-4',    eno: 'E420', category: 'Sweetener',    use: 'Humectant / Sweetener' },
  { name: 'Sucralose',                    cas: '56038-13-2', eno: 'E955', category: 'Sweetener',    use: 'High-intensity sweetener' },
  { name: 'Xanthan Gum',                  cas: '11138-66-2', eno: 'E415', category: 'Hydrocolloid', use: 'Thickener / Stabiliser' },
  { name: 'Xylitol',                      cas: '87-99-0',    eno: 'E967', category: 'Sweetener',    use: 'Bulk sweetener / Dental' },
]

export const dyeListing: DyeItem[] = [
  { name: 'Acid Blue 9 (Brilliant Blue FCF)',              cas: '3844-45-9',  ci: 'CI 42090', category: 'Acid Dye',        use: 'Food / Pharma / Textile' },
  { name: 'Acid Red 14 (Azorubine)',                       cas: '3567-69-9',  ci: 'CI 14720', category: 'Acid Dye',        use: 'Food / Pharma' },
  { name: 'Acid Yellow 23 (Tartrazine)',                   cas: '1934-21-0',  ci: 'CI 19140', category: 'Acid Dye',        use: 'Food / Pharma' },
  { name: 'Allura Red AC (Red 40)',                        cas: '25956-17-6', ci: 'CI 16035', category: 'Azo Dye',         use: 'Food / Cosmetics' },
  { name: 'Beta-Carotene',                                 cas: '7235-40-7',  ci: 'CI 40800', category: 'Natural Dye',     use: 'Food / Nutraceutical' },
  { name: 'Brilliant Blue FCF',                            cas: '3844-45-9',  ci: 'CI 42090', category: 'Triphenylmethane',use: 'Food / Textiles' },
  { name: 'Carmine (Cochineal Red)',                       cas: '1390-65-4',  ci: 'CI 75470', category: 'Natural Dye',     use: 'Food / Cosmetics' },
  { name: 'Crystal Violet (Gentian Violet)',               cas: '548-62-9',   ci: 'CI 42555', category: 'Basic Dye',       use: 'Staining / Medical' },
  { name: 'Disperse Blue 1',                               cas: '2475-45-8',  ci: 'CI 64500', category: 'Disperse Dye',    use: 'Textile / Plastics' },
  { name: 'Erythrosine B (FD&C Red No. 3)',               cas: '16423-68-0', ci: 'CI 45430', category: 'Xanthene',        use: 'Food / Pharma' },
  { name: 'Fast Green FCF',                                cas: '2353-45-9',  ci: 'CI 42053', category: 'Triphenylmethane',use: 'Food / Textile' },
  { name: 'Indigo Carmine (FD&C Blue No. 2)',             cas: '860-22-0',   ci: 'CI 73015', category: 'Indigoid',        use: 'Food / Pharma' },
  { name: 'Methylene Blue',                                cas: '61-73-4',    ci: 'CI 52015', category: 'Phenothiazine',   use: 'Medical / Staining' },
  { name: 'Ponceau 4R (Cochineal Red A)',                  cas: '2611-82-7',  ci: 'CI 16255', category: 'Azo Dye',         use: 'Food / Pharma' },
  { name: 'Reactive Blue 19',                              cas: '2580-78-1',  ci: 'CI 61200', category: 'Reactive Dye',    use: 'Textile' },
  { name: 'Rhodamine B',                                   cas: '81-88-9',    ci: 'CI 45170', category: 'Xanthene',        use: 'Fluorescent / Staining' },
  { name: 'Rose Bengal',                                   cas: '632-69-9',   ci: 'CI 45440', category: 'Xanthene',        use: 'Medical / Diagnostic' },
  { name: 'Sudan IV (Scarlet Red)',                        cas: '85-83-6',    ci: 'CI 26105', category: 'Azo Dye',         use: 'Biological Staining' },
  { name: 'Sunset Yellow FCF (FD&C Yellow 6)',             cas: '2783-94-0',  ci: 'CI 15985', category: 'Azo Dye',         use: 'Food / Pharma / Cosmetics' },
  { name: 'Vat Blue 1 (Indanthrene Blue)',                 cas: '81-77-6',    ci: 'CI 69800', category: 'Vat Dye',         use: 'Textile' },
  { name: 'Aniline',                                       cas: '62-53-3',    ci: '—',        category: 'Intermediate',    use: 'Dye Synthesis' },
  { name: 'H-Acid',                                        cas: '90-20-0',    ci: '—',        category: 'Intermediate',    use: 'Azo Dye Synthesis' },
  { name: 'J-Acid',                                        cas: '87-02-5',    ci: '—',        category: 'Intermediate',    use: 'Dye Synthesis' },
  { name: 'Naphthylamine Sulfonic Acids',                  cas: 'Various',    ci: '—',        category: 'Intermediate',    use: 'Azo Dye Synthesis' },
]

export const impurityListing: ImpurityItem[] = [
  { name: 'Aspirin Impurity A (Salicylic Acid)',        cas: '69-72-7',      api: 'Aspirin',       grade: 'EP Reference Standard' },
  { name: 'Atorvastatin Impurity C',                    cas: '1146299-67-3', api: 'Atorvastatin',  grade: 'EP Reference Standard' },
  { name: 'Ciprofloxacin Impurity B',                   cas: '93107-08-5',   api: 'Ciprofloxacin', grade: 'EP Reference Standard' },
  { name: 'Metformin Impurity A',                       cas: '56-03-1',      api: 'Metformin',     grade: 'EP Reference Standard' },
  { name: 'Omeprazole Impurity B',                      cas: '72742-95-1',   api: 'Omeprazole',    grade: 'EP Reference Standard' },
  { name: 'Paracetamol Impurity A (4-Aminophenol)',     cas: '123-30-8',     api: 'Paracetamol',   grade: 'USP/EP Reference Standard' },
  { name: 'Paracetamol Impurity B (4-Chloroacetanilide)',cas: '539-03-7',    api: 'Paracetamol',   grade: 'EP Reference Standard' },
  { name: 'Azithromycin Impurity F',                    cas: '1224430-71-0', api: 'Azithromycin',  grade: 'EP Reference Standard' },
  { name: 'Pantoprazole Impurity A',                    cas: '102625-64-9',  api: 'Pantoprazole',  grade: 'EP Reference Standard' },
  { name: 'Ibuprofen Impurity B',                       cas: '536-66-3',     api: 'Ibuprofen',     grade: 'EP Reference Standard' },
  { name: 'Fluconazole Impurity A',                     cas: '86386-73-4',   api: 'Fluconazole',   grade: 'EP Reference Standard' },
  { name: 'Simvastatin Impurity A',                     cas: '79902-63-9',   api: 'Simvastatin',   grade: 'USP Reference Standard' },
  { name: 'Rosuvastatin Impurity A',                    cas: '287714-41-4',  api: 'Rosuvastatin',  grade: 'EP Reference Standard' },
  { name: 'Amlodipine Besylate Impurity A',             cas: '3149-28-8',    api: 'Amlodipine',    grade: 'EP Reference Standard' },
  { name: 'Diclofenac Sodium Impurity B',               cas: '6968-79-9',    api: 'Diclofenac',    grade: 'EP Reference Standard' },
  { name: 'Metronidazole Impurity B',                   cas: '3132-64-7',    api: 'Metronidazole', grade: 'EP Reference Standard' },
  { name: 'Pregabalin Impurity A',                      cas: '148553-50-8',  api: 'Pregabalin',    grade: 'EP Reference Standard' },
  { name: 'Gabapentin Impurity A',                      cas: '60142-96-3',   api: 'Gabapentin',    grade: 'EP Reference Standard' },
]

export const organicListing: OrganicInorganicItem[] = [
  { name: 'Acetic Anhydride',      cas: '108-24-7',  grade: 'AR',   type: 'Organic' },
  { name: 'Acetonitrile (HPLC)',   cas: '75-05-8',   grade: 'HPLC', type: 'Organic' },
  { name: 'Benzaldehyde',          cas: '100-52-7',  grade: 'LR',   type: 'Organic' },
  { name: 'n-Butanol',             cas: '71-36-3',   grade: 'LR',   type: 'Organic' },
  { name: 'Carbon Disulfide',      cas: '75-15-0',   grade: 'LR',   type: 'Organic' },
  { name: 'Cyclohexane',           cas: '110-82-7',  grade: 'LR',   type: 'Organic' },
  { name: 'Dichlorobenzene (o)',   cas: '95-50-1',   grade: 'LR',   type: 'Organic' },
  { name: 'Dimethyl Sulfate',      cas: '77-78-1',   grade: 'LR',   type: 'Organic' },
  { name: 'Ethylene Glycol',       cas: '107-21-1',  grade: 'LR',   type: 'Organic' },
  { name: 'Formic Acid',           cas: '64-18-6',   grade: 'AR',   type: 'Organic' },
  { name: 'Methyl Ethyl Ketone',   cas: '78-93-3',   grade: 'LR',   type: 'Organic' },
  { name: 'n-Pentane',             cas: '109-66-0',  grade: 'AR',   type: 'Organic' },
  { name: 'Propionic Acid',        cas: '79-09-4',   grade: 'LR',   type: 'Organic' },
  { name: 'Pyridine',              cas: '110-86-1',  grade: 'AR',   type: 'Organic' },
  { name: 'Tetrahydrofuran',       cas: '109-99-9',  grade: 'AR',   type: 'Organic' },
  { name: 'Trimethylamine',        cas: '75-50-3',   grade: 'LR',   type: 'Organic' },
]

export const inorganicListing: OrganicInorganicItem[] = [
  { name: 'Aluminium Chloride',             cas: '7446-70-0',  grade: 'LR', type: 'Inorganic' },
  { name: 'Aluminium Sulfate',              cas: '10043-01-3', grade: 'LR', type: 'Inorganic' },
  { name: 'Ammonium Nitrate',               cas: '6484-52-2',  grade: 'LR', type: 'Inorganic' },
  { name: 'Ammonium Sulfate',               cas: '7783-20-2',  grade: 'LR', type: 'Inorganic' },
  { name: 'Calcium Carbonate (Precipitated)',cas: '471-34-1',  grade: 'LR', type: 'Inorganic' },
  { name: 'Copper Sulfate Pentahydrate',     cas: '7758-99-8', grade: 'LR', type: 'Inorganic' },
  { name: 'Ferric Chloride',                cas: '7705-08-0',  grade: 'LR', type: 'Inorganic' },
  { name: 'Magnesium Chloride Hexahydrate', cas: '7791-18-6',  grade: 'LR', type: 'Inorganic' },
  { name: 'Manganese Sulfate Monohydrate',  cas: '10034-96-5', grade: 'LR', type: 'Inorganic' },
  { name: 'Potassium Chloride',             cas: '7447-40-7',  grade: 'LR', type: 'Inorganic' },
  { name: 'Potassium Nitrate',              cas: '7757-79-1',  grade: 'LR', type: 'Inorganic' },
  { name: 'Silver Nitrate',                 cas: '7761-88-8',  grade: 'AR', type: 'Inorganic' },
  { name: 'Sodium Carbonate',               cas: '497-19-8',   grade: 'LR', type: 'Inorganic' },
  { name: 'Sodium Sulfate Anhydrous',       cas: '7757-82-6',  grade: 'LR', type: 'Inorganic' },
  { name: 'Zinc Chloride',                  cas: '7646-85-7',  grade: 'LR', type: 'Inorganic' },
]

export const pelletListing: PelletItem[] = [
  { name: 'MCC Pellets (Cellets 90)',        size: '90–150 µm',   type: 'Starter Pellets', use: 'Layering substrate for API coating' },
  { name: 'MCC Pellets (Cellets 200)',       size: '150–250 µm',  type: 'Starter Pellets', use: 'Layering substrate / IR pellets' },
  { name: 'MCC Pellets (Cellets 350)',       size: '300–400 µm',  type: 'Starter Pellets', use: 'Modified release systems' },
  { name: 'MCC Pellets (Cellets 500)',       size: '400–600 µm',  type: 'Starter Pellets', use: 'Controlled release pellets' },
  { name: 'Sugar Pellets (Non-Pareil)',      size: '250–500 µm',  type: 'Starter Pellets', use: 'API layering for oral dosage' },
  { name: 'Omeprazole Pellets 8.5%',        size: '400–800 µm',  type: 'API Pellets',     use: 'Enteric-coated capsule filling' },
  { name: 'Omeprazole Pellets 8.5% (EC)',   size: '400–800 µm',  type: 'Enteric Coated',  use: 'Acid-resistant pellets for PPIs' },
  { name: 'Esomeprazole Pellets 8.5%',      size: '400–800 µm',  type: 'Enteric Coated',  use: 'Enteric-coated capsule filling' },
  { name: 'Pantoprazole Pellets 8.5%',      size: '400–800 µm',  type: 'Enteric Coated',  use: 'Enteric-coated capsule filling' },
  { name: 'Rabeprazole Pellets 8.5%',       size: '400–800 µm',  type: 'Enteric Coated',  use: 'Acid-resistant pellets' },
  { name: 'Lansoprazole Pellets 8.5%',      size: '400–800 µm',  type: 'Enteric Coated',  use: 'Enteric-coated capsule filling' },
  { name: 'Metformin Extended-Release',     size: '600–1000 µm', type: 'ER Pellets',      use: 'Once-daily extended release' },
  { name: 'Metoprolol Succinate ER',        size: '500–800 µm',  type: 'ER Pellets',      use: 'Modified-release cardiovascular' },
  { name: 'Venlafaxine ER Pellets',         size: '500–900 µm',  type: 'ER Pellets',      use: 'Once-daily depression / anxiety' },
  { name: 'Tramadol HCl ER Pellets',        size: '600–900 µm',  type: 'ER Pellets',      use: 'Controlled-release analgesic' },
  { name: 'Aspirin Enteric-Coated',         size: '500–1000 µm', type: 'Enteric Coated',  use: 'GI-protective aspirin' },
  { name: 'Diclofenac Sodium EC Pellets',   size: '500–800 µm',  type: 'Enteric Coated',  use: 'GI-protective NSAID' },
  { name: 'Iron Chelate Pellets',           size: '300–600 µm',  type: 'Specialty',       use: 'Iron supplement capsule filling' },
  { name: 'Vitamin C SR Pellets',           size: '400–700 µm',  type: 'SR Pellets',      use: 'Sustained-release Vitamin C' },
  { name: 'Zinc Sulfate Pellets',           size: '300–500 µm',  type: 'Specialty',       use: 'Zinc supplement filling' },
  { name: 'Ambroxol Hydrochloride SR Pellets 40% w/w', size: '500–800 µm', type: 'SR Pellets', use: 'Sustained-release mucolytic capsules' },
]
