export type PageRegistryEntry = {
  path: string
  label: string
  group: string
  defaultTitle: string
  defaultDescription: string
  defaultKeywords: string
}

// Common brand + corporate keywords reused across many pages.
const BRAND = 'Astonea Labs, Astonea Labs Limited, BSE-SME, L24304CH2017PLC041482, Chandigarh pharmaceutical company'
const PHARMA = 'pharmaceutical manufacturer India, contract manufacturing, third-party manufacturing, GMP-certified pharma, WHO-GMP manufacturer'
const CHEM = 'specialty chemicals, APIs, excipients, intermediates'
const IR = 'investor relations, BSE-SME listed, shareholder information, corporate disclosures'
const SEBI = 'SEBI LODR, SEBI Listing Obligations, regulatory disclosures, BSE filings'
const GOV = 'corporate governance, board of directors, board policies, compliance'

export const PAGE_REGISTRY: PageRegistryEntry[] = [
  // Core
  { path: '/',                     group: 'Core',     label: 'Home',                   defaultTitle: 'Astonea Labs Limited', defaultDescription: 'A BSE-SME listed pharmaceutical and specialty chemicals company.', defaultKeywords: `${BRAND}, ${PHARMA}, pharma and cosmetics manufacturer, BSE-SME pharma stock` },
  { path: '/about-us',             group: 'Core',     label: 'About Us',               defaultTitle: 'About Us', defaultDescription: 'Our story, values, and the people behind Astonea Labs Limited.', defaultKeywords: `${BRAND}, about Astonea Labs, Ashish Gulati, founder, company history, pharma company Chandigarh, BSE-SME pharma` },
  { path: '/vision-and-mission',   group: 'Core',     label: 'Vision & Mission',       defaultTitle: 'Vision & Mission', defaultDescription: 'Vision and mission of Astonea Labs Limited.', defaultKeywords: `${BRAND}, vision, mission, values, sustainability, quality manufacturing` },
  { path: '/what-we-do',           group: 'Core',     label: 'What We Do',             defaultTitle: 'What We Do', defaultDescription: 'Capabilities and operations across the Astonea Labs portfolio.', defaultKeywords: `${BRAND}, ${PHARMA}, contract manufacturing capabilities, cosmetics manufacturing, formulation development, regulatory support` },
  { path: '/key-milestone',        group: 'Core',     label: 'Key Milestones',         defaultTitle: 'Key Milestones', defaultDescription: 'Key milestones in the journey of Astonea Labs Limited.', defaultKeywords: `${BRAND}, milestones, company timeline, IPO, BSE-SME listing, growth journey` },
  { path: '/leadership-panel',     group: 'Core',     label: 'Leadership',             defaultTitle: 'Leadership', defaultDescription: 'Senior leadership at Astonea Labs Limited.', defaultKeywords: `${BRAND}, leadership team, senior management, KMP, executives, management team` },
  { path: '/board-of-directors',   group: 'Core',     label: 'Board of Directors',     defaultTitle: 'Board of Directors', defaultDescription: 'Board of Directors at Astonea Labs Limited.', defaultKeywords: `${BRAND}, board of directors, independent directors, executive directors, ${GOV}, directors profile` },
  { path: '/csr',                  group: 'Core',     label: 'CSR',                    defaultTitle: 'CSR', defaultDescription: 'Corporate social responsibility at Astonea Labs Limited.', defaultKeywords: `${BRAND}, CSR, corporate social responsibility, sustainability, social impact, Astonea Foundation, ecological preservation` },
  { path: '/career',               group: 'Core',     label: 'Career',                 defaultTitle: 'Career', defaultDescription: 'Career opportunities at Astonea Labs Limited.', defaultKeywords: `${BRAND}, careers, jobs, pharma jobs Chandigarh, employment, hiring, work at Astonea` },
  { path: '/contact-us',           group: 'Core',     label: 'Contact Us',             defaultTitle: 'Contact Us', defaultDescription: 'Get in touch with Astonea Labs Limited.', defaultKeywords: `${BRAND}, contact, registered office Chandigarh, factory Panchkula, phone, email, sales enquiry` },
  { path: '/support',              group: 'Core',     label: 'Customer Support',       defaultTitle: 'Customer Support', defaultDescription: 'Raise a support ticket or file a complaint with Astonea Labs. Track every reply on a single status page.', defaultKeywords: `${BRAND}, customer support, complaints, support ticket, helpdesk, post-sales support` },
  { path: '/support/new',          group: 'Core',     label: 'Raise a Ticket',         defaultTitle: 'Raise a support ticket', defaultDescription: 'Send Astonea Labs your support enquiry or complaint. Verify by SMS and receive a tracked email link.', defaultKeywords: `${BRAND}, raise support ticket, file complaint, customer enquiry, helpdesk request` },

  // Products & manufacturing
  { path: '/products',                            group: 'Products', label: 'Products',                defaultTitle: 'Products', defaultDescription: 'Astonea Labs product portfolio across APIs, excipients and specialty chemicals.', defaultKeywords: `${BRAND}, ${CHEM}, pharmaceutical products, nutraceuticals, herbal extracts, food chemicals, dyes, intermediates, impurities, pellets, industrial chemicals` },
  { path: '/products/apis',                       group: 'Products', label: 'APIs',                    defaultTitle: 'Active Pharmaceutical Ingredients (APIs)', defaultDescription: 'Active Pharmaceutical Ingredients (APIs).', defaultKeywords: `${BRAND}, APIs, Active Pharmaceutical Ingredients, API manufacturer India, USDMF, EDQM, generic APIs, custom synthesis` },
  { path: '/products/excipients',                 group: 'Products', label: 'Excipients',              defaultTitle: 'Pharmaceutical Excipients', defaultDescription: 'Pharmaceutical excipients.', defaultKeywords: `${BRAND}, excipients, pharmaceutical excipients, IP grade, BP grade, USP grade, NF grade, binders, fillers, coatings` },
  { path: '/products/industrial-chemicals',       group: 'Products', label: 'Industrial Chemicals',    defaultTitle: 'Industrial Chemicals', defaultDescription: 'Industrial chemicals.', defaultKeywords: `${BRAND}, industrial chemicals, solvents, intermediates, bulk chemicals, industrial-grade chemicals, B2B chemicals` },
  { path: '/products/nutraceuticals',             group: 'Products', label: 'Nutraceuticals',          defaultTitle: 'Nutraceuticals', defaultDescription: 'Nutraceuticals.', defaultKeywords: `${BRAND}, nutraceuticals, dietary supplements, vitamins, minerals, herbal nutraceuticals, AYUSH nutraceuticals, functional foods` },
  { path: '/products/food-chemicals',             group: 'Products', label: 'Food Chemicals',          defaultTitle: 'Food Chemicals', defaultDescription: 'Food-grade chemicals.', defaultKeywords: `${BRAND}, food chemicals, food grade chemicals, FSSAI approved, food additives, food-grade ingredients, food preservatives` },
  { path: '/products/herbal-extracts',            group: 'Products', label: 'Herbal Extracts',         defaultTitle: 'Herbal Extracts', defaultDescription: 'Herbal extracts.', defaultKeywords: `${BRAND}, herbal extracts, Ayurvedic extracts, AYUSH extracts, botanical extracts, standardized extracts, natural extracts manufacturer` },
  { path: '/products/dyes-and-intermediates',     group: 'Products', label: 'Dyes & Intermediates',    defaultTitle: 'Dyes & Intermediates', defaultDescription: 'Dyes and intermediates.', defaultKeywords: `${BRAND}, dyes, dye intermediates, reactive dyes, acid dyes, dispersing agents, textile dyes` },
  { path: '/products/impurities',                 group: 'Products', label: 'Impurities',              defaultTitle: 'Pharmaceutical Impurities', defaultDescription: 'Pharmaceutical impurities.', defaultKeywords: `${BRAND}, pharmaceutical impurities, reference standards, USP impurities, EP impurities, related substances, impurity standards` },
  { path: '/products/organic-inorganic',          group: 'Products', label: 'Organic / Inorganic',     defaultTitle: 'Organic & Inorganic Chemicals', defaultDescription: 'Organic and inorganic chemicals.', defaultKeywords: `${BRAND}, organic chemicals, inorganic chemicals, fine chemicals, specialty chemicals, laboratory reagents` },
  { path: '/products/pellets',                    group: 'Products', label: 'Pellets',                 defaultTitle: 'Pellets', defaultDescription: 'Pellets.', defaultKeywords: `${BRAND}, pellets, pharmaceutical pellets, drug-loaded pellets, controlled-release pellets, MUPS pellets, pelletization` },
  { path: '/products/intermediates',              group: 'Products', label: 'Intermediates',           defaultTitle: 'Pharmaceutical Intermediates', defaultDescription: 'Pharmaceutical intermediates.', defaultKeywords: `${BRAND}, pharmaceutical intermediates, API intermediates, advanced intermediates, key starting materials, KSM` },
  { path: '/manufacturing-facility',              group: 'Products', label: 'Manufacturing Facility',  defaultTitle: 'Manufacturing Facility', defaultDescription: 'Our GMP-compliant manufacturing facility in Panchkula, Haryana.', defaultKeywords: `${BRAND}, manufacturing facility Panchkula, GMP facility, pharma factory Haryana, production capacity, manufacturing plant` },
  { path: '/certifications',                      group: 'Products', label: 'Certifications',          defaultTitle: 'Certifications', defaultDescription: 'Certifications and accreditations.', defaultKeywords: `${BRAND}, WHO-GMP, ISO 9001, cGMP, AYUSH approved, FSSAI, USFDA OTC, quality certifications, regulatory approvals` },

  // Investor Relations
  { path: '/investor-insights',                    group: 'Investor', label: 'Investor Insights',           defaultTitle: 'Investor Insights', defaultDescription: 'Central hub for investor relations.', defaultKeywords: `${BRAND}, ${IR}, investor insights, financial reports, disclosures, BSE-SME listed company` },
  { path: '/annual-reports',                       group: 'Investor', label: 'Annual Reports',              defaultTitle: 'Annual Reports', defaultDescription: 'Annual reports of Astonea Labs Limited.', defaultKeywords: `${BRAND}, ${IR}, annual report, annual filing, director report, financial year report, ${SEBI}` },
  { path: '/financial-results',                    group: 'Investor', label: 'Financial Results',           defaultTitle: 'Financial Results', defaultDescription: 'Quarterly and annual financial statements.', defaultKeywords: `${BRAND}, ${IR}, financial results, quarterly results, half-yearly results, audited financials, ${SEBI}` },
  { path: '/board-meetings',                       group: 'Investor', label: 'Board Meetings',              defaultTitle: 'Board Meetings', defaultDescription: 'Intimations and outcomes of Board of Directors meetings.', defaultKeywords: `${BRAND}, board meetings, board meeting outcomes, board meeting intimation, ${SEBI}, Regulation 29 SEBI LODR` },
  { path: '/agm',                                  group: 'Investor', label: 'AGM',                         defaultTitle: 'Annual General Meeting (AGM)', defaultDescription: 'Annual General Meetings.', defaultKeywords: `${BRAND}, AGM, annual general meeting, AGM notice, AGM proceedings, scrutinizer report, voting results` },
  { path: '/egm',                                  group: 'Investor', label: 'EGM',                         defaultTitle: 'Extraordinary General Meeting (EGM)', defaultDescription: 'Extraordinary General Meetings.', defaultKeywords: `${BRAND}, EGM, extraordinary general meeting, EGM notice, EGM proceedings, scrutinizer report, voting results` },
  { path: '/meetings',                             group: 'Investor', label: 'Meetings',                    defaultTitle: 'Meetings', defaultDescription: 'Meetings hub.', defaultKeywords: `${BRAND}, meetings, AGM, EGM, board meetings, general meetings, shareholder meetings` },
  { path: '/shareholding-pattern',                 group: 'Investor', label: 'Shareholding Pattern',        defaultTitle: 'Shareholding Pattern', defaultDescription: 'Quarterly shareholding pattern disclosures.', defaultKeywords: `${BRAND}, shareholding pattern, Regulation 31 SEBI LODR, promoter holding, public shareholding, share structure` },
  { path: '/trading-window-closure',               group: 'Investor', label: 'Trading Window Closure',      defaultTitle: 'Trading Window Closure', defaultDescription: 'Trading window closure intimations.', defaultKeywords: `${BRAND}, trading window closure, SEBI insider trading, PIT regulations, prohibition of insider trading, designated persons` },
  { path: '/related-party-transactions',           group: 'Investor', label: 'Related Party Transactions',  defaultTitle: 'Related Party Transactions', defaultDescription: 'Related party transaction disclosures.', defaultKeywords: `${BRAND}, related party transactions, RPT, Regulation 23 SEBI LODR, RPT disclosure, half-yearly RPT` },
  { path: '/investor-grievances',                  group: 'Investor', label: 'Investor Grievances',         defaultTitle: 'Investor Grievances', defaultDescription: 'Grievance mechanism.', defaultKeywords: `${BRAND}, investor grievances, SCORES, complaint redressal, compliance officer, shareholder grievance` },
  { path: '/registrar-share-transfer-agent',       group: 'Investor', label: 'Registrar (RTA)',             defaultTitle: 'Registrar & Share Transfer Agent', defaultDescription: 'Registrar and Share Transfer Agent details.', defaultKeywords: `${BRAND}, RTA, registrar share transfer agent, share transfer, dematerialisation, BSE-SME` },

  // SEBI Disclosures
  { path: '/sebi-lodr-regulation-30-disclosures',  group: 'SEBI',     label: 'Reg 30 Disclosures',          defaultTitle: 'SEBI LODR Regulation 30 Disclosures', defaultDescription: 'Event-based disclosures under SEBI LODR Regulation 30.', defaultKeywords: `${BRAND}, ${SEBI}, Regulation 30 SEBI LODR, material event disclosure, intimation to exchange, prompt disclosure` },
  { path: '/sebi-lodr-regulation-46-disclosures',  group: 'SEBI',     label: 'Reg 46 Disclosures',          defaultTitle: 'SEBI LODR Regulation 46 Disclosures', defaultDescription: 'Annual corporate governance disclosures.', defaultKeywords: `${BRAND}, ${SEBI}, Regulation 46 SEBI LODR, website disclosures, corporate governance disclosures, mandatory disclosures` },
  { path: '/integrated-filings',                   group: 'SEBI',     label: 'Integrated Filings',          defaultTitle: 'Integrated Filings', defaultDescription: 'Quarterly BSE filings.', defaultKeywords: `${BRAND}, integrated filings, SEBI integrated filing framework, quarterly compliance filing, BSE compliance` },
  { path: '/integrated-finance',                   group: 'SEBI',     label: 'Integrated Finance',          defaultTitle: 'Integrated Finance', defaultDescription: 'Integrated finance disclosures.', defaultKeywords: `${BRAND}, integrated finance filings, half-yearly integrated filing, yearly integrated filing, BSE finance filing` },
  { path: '/integrated-governance',                group: 'SEBI',     label: 'Integrated Governance',       defaultTitle: 'Integrated Governance', defaultDescription: 'Integrated governance disclosures.', defaultKeywords: `${BRAND}, integrated governance filings, quarterly governance, ${SEBI}, BSE governance filing` },

  // Governance
  { path: '/corporate-governance',                 group: 'Governance', label: 'Corporate Governance',      defaultTitle: 'Corporate Governance', defaultDescription: 'Governance framework.', defaultKeywords: `${BRAND}, ${GOV}, board committees, governance framework, audit committee, NRC, stakeholders relationship committee` },
  { path: '/corporate-documents',                  group: 'Governance', label: 'Corporate Documents',       defaultTitle: 'Corporate Documents', defaultDescription: 'Policy documents.', defaultKeywords: `${BRAND}, corporate documents, MOA, AOA, Memorandum of Association, Articles of Association, statutory documents` },
  { path: '/corporate-announcements',              group: 'Governance', label: 'Corporate Announcements',   defaultTitle: 'Corporate Announcements', defaultDescription: 'Material announcements.', defaultKeywords: `${BRAND}, corporate announcements, material events, stock exchange announcements, BSE announcements, ${SEBI}` },
  { path: '/governance-policies-codes-and-frameworks', group: 'Governance', label: 'Policies / Codes / Frameworks', defaultTitle: 'Policies, Codes & Frameworks', defaultDescription: 'Governance policies hub.', defaultKeywords: `${BRAND}, ${GOV}, board policies, code of conduct, governance frameworks, statutory policies` },
  { path: '/policies',                             group: 'Governance', label: 'Policies',                  defaultTitle: 'Policies', defaultDescription: 'Board-approved governance policies.', defaultKeywords: `${BRAND}, board policies, POSH policy, whistle blower policy, vigil mechanism, RPT policy, CSR policy, dividend policy` },
  { path: '/codes',                                group: 'Governance', label: 'Codes',                     defaultTitle: 'Codes', defaultDescription: 'Codes of conduct.', defaultKeywords: `${BRAND}, code of conduct, insider trading code, PIT code, fair disclosure code, code of conduct for directors` },
  { path: '/frameworks',                           group: 'Governance', label: 'Frameworks',                defaultTitle: 'Frameworks', defaultDescription: 'Governance frameworks.', defaultKeywords: `${BRAND}, governance frameworks, board evaluation framework, performance evaluation framework, independent directors framework` },
  { path: '/group-companies',                      group: 'Governance', label: 'Group Companies',           defaultTitle: 'Group Companies', defaultDescription: 'Group entities and subsidiaries.', defaultKeywords: `${BRAND}, group companies, subsidiaries, Ascot Biolabs, Shinto Organics, Astonea One, Chemist India, Astonea Foundation` },
  { path: '/subsidiaries',                         group: 'Governance', label: 'Subsidiaries',              defaultTitle: 'Subsidiaries', defaultDescription: 'Subsidiary information.', defaultKeywords: `${BRAND}, subsidiaries, Astonea LLC USA, wholly owned subsidiary, subsidiary financials, group structure` },
  { path: '/newspaper-publications',               group: 'Governance', label: 'Newspaper Publications',    defaultTitle: 'Newspaper Publications', defaultDescription: 'Statutory newspaper publications.', defaultKeywords: `${BRAND}, newspaper publications, financial results publication, statutory notices, public notice, ${SEBI}` },
]

export const PAGE_REGISTRY_BY_PATH: Record<string, PageRegistryEntry> = Object.fromEntries(
  PAGE_REGISTRY.map((p) => [p.path, p]),
)
